version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: privacy-guardian-backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    depends_on:
      - chroma
    environment:
      - CHROMA_HOST=chroma
      - OLLAMA_HOST=ollama

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: privacy-guardian-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0

  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/.chroma/index
    environment:
      - IS_PERSISTENT=TRUE

volumes:
  ollama_data:
  chroma_data:
